IsSaveExOnQuit: true
AutoSaveData: true
ExDir: Experiment
DataDir: Data
ExLogic: ConditionTestLogic
NotifyParams:
- CondIndex
- CONDSTATE
- CondRepeat
AntiAliasing: 2
AnisotropicFilterLevel: 5
FixedDeltaTime: 1000000
IsShowInactiveEnvParam: false
IsShowEnvParamFullName: false
MaxLogEntry: 999
ExHideParams:
- Cond
- CondTest
- EnvParam
- Param
- Log
- Subject_Log
- DataPath
CrossEnvInheritRulePath: CrossEnvInheritRule.yaml
