IsSaveExOnQuit: true
AutoSaveData: true
SaveDataFormat: YAML
ExDir: Experiment
DataDir: Data
ExLogic: ConditionTestLogic
EnvCrossInheritRulePath: EnvCrossInheritRule.yaml
NotifyParams:
- CondIndex
- CondRepeat
- CONDSTATE
AntiAliasing: 2
AnisotropicFilterLevel: 5
FixedDeltaTime: 1000000
IsShowInactiveEnvParam: false
IsShowEnvParamFullName: false
MaxLogEntry: 999
ExHideParams:
- Cond
- CondTest
- EnvParam
- Param
- Log
- Subject_Log
- DataPath
- ExInheritParam
- EnvInheritParam
NotifyLatency: 200
ExLatencyError: 20
OnlineSignalLatency: 50
ParallelPort1: 45072
ParallelPort2: 53264
ParallelPort3: 53264
StartCh: 2
StopCh: 3
ConditionCh: 0
SignalCh1: 1
SignalCh2: 4
SignalCh3: 5
OICh: 0
SerialPort1: COM3
SerialPort2: COM4
SerialPort3: COM5
MarkPulseWidth: 21
WaveHighDur: 5
WaveLowDur: 20
FirstTestID: ConditionTest
