IsSaveExOnQuit: true
AutoSaveData: true
ExDir: Experiment
DataDir: Data
ExLogic: ConditionTestLogic
NotifyParams:
- CondIndex
- CONDSTATE
- CondRepeat
AntiAliasing: 2
AnisotropicFilterLevel: 5
LogicTick: 9.99999975E-05
IsShowInactiveEnvParam: false
IsShowEnvParamFullName: false
MaxLogEntry: 999
ExHideParams:
- Cond
- CondTest
- EnvParam
- Param
- Log
- Subject_Log
- DataPath
CrossEnvInheritRulePath: DefaultCrossEnvInheritRule.yaml
