IsSaveExOnQuit: true
ExDir: Experiment
DataDir: Data
ExLogic: ConditionTestLogic
NotifyParams:
- CondIndex
- CONDSTATE
AntiAliasing: 2
AnisotropicFilterLevel: 5
LogicTick: 0.0001
IsShowInactiveEnvParam: false
IsShowEnvParamFullName: false
MaxLogEntry: 999
ExHideParams:
- Cond
- CondTest
- EnvParam
- Param
- Log
- Subject_Log
AutoSaveData: true
