issaveexonquit: true
exdefdir: Experiment
condtestdir: ConditionTest
defaultexperimentlogic: ConditionTest
antialiasing: 2
anisotropicfilterlevel: 5
logictick: 0.0001
isshowinactiveenvparam: false
isshowenvparamfullname: false
maxlogentry: 999
