IsSaveExOnQuit: true
AutoSaveData: true
ExDir: Experiment
DataDir: Data
ExLogic: ConditionTestLogic
NotifyParams:
- CondIndex
- CONDSTATE
- CondRepeat
AntiAliasing: 2
AnisotropicFilterLevel: 5
FixedDeltaTime: 1000000
IsShowInactiveEnvParam: false
IsShowEnvParamFullName: false
MaxLogEntry: 999
CrossEnvInheritRulePath: CrossEnvInheritRule.yaml
ParallelPort1: 49168
ParallelPort2: 49168
ParallelPort3: 49168
COMPort1: COM3
COMPort2: COM4
COMPort3: COM5
StartBit: 2
StopBit: 3
ConditionBit: 0
Signal1Bit: 1
Signal2Bit: 4
Signal3Bit: 5
NotifyLatency: 200
ExLatencyError: 20
OnlineSignalLatency: 50
MarkPulseWidth: 21
ParallelPortSquareWaveHighDur: 5
ParallelPortSquareWaveLowDur: 20
ExHideParams:
- Cond
- CondTest
- EnvParam
- Param
- Log
- Subject_Log
- DataPath
- ExInheritParam
- EnvInheritParam
