IsSaveExOnQuit: true
AutoSaveData: true
SaveConfigInData: true
SaveConfigDisplayMeasurementInData: false
SaveDataFormat: YAML
ExDir: Experiment\SNL-C
DataDir: Data
ExLogic: Experica.ConditionTestLogic
NotifyParams:
- CondIndex
- Event
- SyncEvent
AntiAliasing: 2
AnisotropicFilterLevel: 5
FixedDeltaTime: 1000000
VSyncCount: 1
MaxQueuedFrames: 2
FrameTimer: true
FullScreenMode: ExclusiveFullScreen
IsShowInactiveEnvParam: false
IsShowEnvParamFullName: false
MaxLogEntry: 999
ExHideParams:
- Cond
- CondTest
- EnvParam
- Param
- Subject_Log
- DataPath
- ExInheritParam
- EnvInheritParam
- Version
- EventSyncProtocol
- Config
FirstTestID: ConditionTest
ExperimenterAddress:
  Alex: 4109829463@mms.att.net
  PL: 8584056165@mms.att.net
SyncFrameTimeOut: 4
NotifyLatency: 200
MaxDisplayLatencyError: 20
OnlineSignalLatency: 50
MCCDevice: 1208FS
MCCDPort: 10
ParallelPort1: 45072
ParallelPort2: 53264
ParallelPort3: 53264
EventSyncCh: 0
EventMeasureCh: 1
StartSyncCh: 2
StopSyncCh: 3
Bits16Ch: 5
SignalCh1: 0
SignalCh2: 1
SignalCh3: 2
SerialPort1: COM3
SerialPort2: COM4
SerialPort3: COM5
RecordHost: 10.1.51.72
RecordHostPort: 4142
Param: {}
EnvCrossInheritRule:
  GratingQuad:
    Quad:
    - Ori
    - Position
    - Diameter
    ImageQuad:
    - Position
    - Diameter
  Quad:
    GratingQuad:
    - Ori
    - Position
    - Diameter
    ImageQuad:
    - Position
    - Diameter
  ImageQuad:
    GratingQuad:
    - Position
    - Diameter
    Quad:
    - Position
    - Diameter
Display:
  ROGPG279Q:
    ID: ROGPG279Q
    Type: LCD
    Latency: 40
    RiseLag: 1
    FallLag: 12.5
    CLUTSize: 24
    FitType: LinearSpline
    IntensityMeasurement: {}
    SpectralMeasurement: {}
  Trinitron:
    ID: Trinitron
    Type: CRT
    Latency: 0
    RiseLag: 0
    FallLag: 0
    CLUTSize: 24
    FitType: LinearSpline
    IntensityMeasurement:
      Y:
      - 10.44
      - 5.5259999999999998
      - 0.51590000000000003
      - 2.4350000000000001
      - 57.479999999999997
      - 18.260000000000002
      - 8.4619999999999997
      - 49.990000000000002
      - 12.98
      - 21.809999999999999
      - 15.43
      - 1.3939999999999999
      - 2.9809999999999999
      - 4.899
      - 8.593
      - 35.590000000000003
      - 1.5309999999999999
      - 0.081710000000000005
      - 10.029999999999999
      - 3.3159999999999998
      - 42.170000000000002
      - 14.67
      - 28.399999999999999
      - 6.1269999999999998
      - 7.173
      - 7.976
      - 20.899999999999999
      - 3.7040000000000002
      Color:
      - 0.5556 0 0 1
      - 0.3333 0 0 1
      - 0 0 0.1111 1
      - 0 0 0.3333 1
      - 0 1 0 1
      - 0.8889 0 0 1
      - 0 0.2222 0 1
      - 0 0.8889 0 1
      - 0.6667 0 0 1
      - 0 0.4444 0 1
      - 0.7778 0 0 1
      - 0.1111 0 0 1
      - 0 0.1111 0 1
      - 0 0 0.5556 1
      - 0 0 0.8889 1
      - 0 0.6667 0 1
      - 0 0 0.2222 1
      - 0 0 0 1
      - 0 0 1 1
      - 0.2222 0 0 1
      - 0 0.7778 0 1
      - 0 0.3333 0 1
      - 0 0.5556 0 1
      - 0 0 0.6667 1
      - 0 0 0.7778 1
      - 0.4444 0 0 1
      - 1 0 0 1
      - 0 0 0.4444 1
    SpectralMeasurement: 
