IsSaveExOnQuit: true
AutoSaveData: true
SaveConfigInData: true
SaveConfigDisplayMeasurementInData: false
SaveDataFormat: YAML
ExDir: Experiment\SNL-C
DataDir: Data
ExLogic: Experica.ConditionTestLogic
NotifyParams:
- CondIndex
- Event
- SyncEvent
AntiAliasing: 2
AnisotropicFilterLevel: 5
FixedDeltaTime: 1000000
VSyncCount: 1
MaxQueuedFrames: 2
FrameTimer: true
FullScreenMode: ExclusiveFullScreen
IsShowInactiveEnvParam: false
IsShowEnvParamFullName: false
MaxLogEntry: 999
ExHideParams:
- Cond
- CondTest
- EnvParam
- Param
- Subject_Log
- DataPath
- ExInheritParam
- EnvInheritParam
- Version
- EventSyncProtocol
- Config
FirstTestID: ConditionTest
ExperimenterAddress:
  Alex: 4109829463@mms.att.net
  PL: 8584056165@mms.att.net
SyncFrameTimeOut: 4
NotifyLatency: 200
MaxDisplayLatencyError: 20
OnlineSignalLatency: 50
MCCDevice: 1208FS
MCCDPort: 10
ParallelPort1: 45072
ParallelPort2: 53264
ParallelPort3: 53264
EventSyncCh: 0
EventMeasureCh: 1
StartSyncCh: 2
StopSyncCh: 3
Bits16Ch: 5
SignalCh1: 0
SignalCh2: 1
SignalCh3: 2
SerialPort1: COM3
SerialPort2: COM4
SerialPort3: COM5
RecordHost: 10.1.51.72
RecordHostPort: 4142
Param: {}
EnvCrossInheritRule:
  GratingQuad:
    Quad:
    - Ori
    - Position
    - Diameter
    ImageQuad:
    - Position
    - Diameter
  Quad:
    GratingQuad:
    - Ori
    - Position
    - Diameter
    ImageQuad:
    - Position
    - Diameter
  ImageQuad:
    GratingQuad:
    - Position
    - Diameter
    Quad:
    - Position
    - Diameter
Display:
  ROGPG279Q:
    ID: ROGPG279Q
    Type: LCD
    Latency: 40
    RiseLag: 1
    FallLag: 12
    CLUTSize: 32
    FitType: LinearSpline
    IntensityMeasurement: {}
    SpectralMeasurement: {}
